# Generated by Django 5.0.3 on 2024-03-10 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_expenses_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
